Website = "https://github.com/azorg/hellofyne"

[Details]
  Icon = "Icon.png"
  Name = "hellofyne"
  ID = "com.example.hellofyne"
  Version = "1.0.0"
  Build = 4

[LinuxAndBSD]
  GenericName = "hellofyne"
  Categories = ["stuff"]
  Comment = "Hello Fyne"
  Keywords = ["fyne", "example"]
